name = "Doks"
license = "MIT"
licenselink = "https://github.com/Science-Night-Studios/sns-docs/blob/master/LICENSE"
description = "Hugo theme for SNS Docs site"

homepage = "https://github.com/Science-Night-Studios/sns-docs"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["security aware", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]
